// Generated by gencpp from file first_try/AddTwoInts.msg
// DO NOT EDIT!


#ifndef FIRST_TRY_MESSAGE_ADDTWOINTS_H
#define FIRST_TRY_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <first_try/AddTwoIntsRequest.h>
#include <first_try/AddTwoIntsResponse.h>


namespace first_try
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace first_try


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::first_try::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::first_try::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::first_try::AddTwoInts > {
  static const char* value()
  {
    return "first_try/AddTwoInts";
  }

  static const char* value(const ::first_try::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::first_try::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::first_try::AddTwoInts > 
template<>
struct MD5Sum< ::first_try::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::first_try::AddTwoInts >::value();
  }
  static const char* value(const ::first_try::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::first_try::AddTwoIntsRequest> should match 
// service_traits::DataType< ::first_try::AddTwoInts > 
template<>
struct DataType< ::first_try::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::first_try::AddTwoInts >::value();
  }
  static const char* value(const ::first_try::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::first_try::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::first_try::AddTwoInts > 
template<>
struct MD5Sum< ::first_try::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::first_try::AddTwoInts >::value();
  }
  static const char* value(const ::first_try::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::first_try::AddTwoIntsResponse> should match 
// service_traits::DataType< ::first_try::AddTwoInts > 
template<>
struct DataType< ::first_try::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::first_try::AddTwoInts >::value();
  }
  static const char* value(const ::first_try::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FIRST_TRY_MESSAGE_ADDTWOINTS_H
